blank_issues_enabled: false
contact_links:
  - name: Questions / Ideas
    url: https://github.com/Jimmybee/stock-tree-full-stack/discussions
    about: Use Discussions for general Q&A and brainstorming.
